### ISSUE TITLE
Better piece sprites

### ISSUE THREAD

**Issue by greenrock64** [greenrock64/UC-Chess#11]
The piece sprites we have currently are a bit choppy. If anyone can source or make some better ones that'd make it look way better.

**Comment by brawlisforwii** [comment]
The better sprites are in yeah?

**Comment by greenrock64** [comment]
Not yet. I've sourced a new set of them that are Creative Commons licensed, but I'll need to add support for Sprite Sheets to use them properly/sanely.

**Comment by greenrock64** [comment]
Added in pull request #18
